kind: pipeline
name: arm

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: alpine
  commands:
  - uname -a

---
kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: alpine
  commands:
  - uname -a

